GNU_INSTALL_ROOT ?= C:/Users/BlanchTrap/Documents/GitHub/ChameleonUltra/tools/arm-toolchain/arm-gnu-toolchain-12.2.rel1-mingw-w64-i686-arm-none-eabi/bin/
GNU_VERSION ?= 12.2.1
GNU_PREFIX ?= arm-none-eabi
