name: PR handler
on:
  pull_request:

concurrency:
  group: pr-build-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  firmware_pipeline:
    name: Build Firmware
    permissions:
      contents: read
    uses: ./.github/workflows/build_firmware.yml
    with:
      checkout-sha: "${{ github.event.pull_request.head.sha }}"
      publish-builder: false
  client_pipeline:
    name: Build Firmware
    permissions:
      contents: read
    uses: ./.github/workflows/build_client.yml
    with:
      checkout-sha: "${{ github.event.pull_request.head.sha }}"
